# Copyright 2015 Antony Riley
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: "DuckLog"
version: "${version}-${project.build.number}"
main: "org.cyberiantiger.minecraft.log.Main"
depend:
        - Vault
commands:
        seen:
                usage: /seen <name|ip>
                description: Show when a name or IP was last used, or all usages.
                permission: ducklog.seen
        audit:
                usage: /audit <name|ip> [<page>]
                desciption: Show an audit of events relating to the specified IP or Name.
                permission: ducklog.audit
        check:
                usage: /check [<name>]
                description: Show information on cumulative login time, and rankup if needed.
                permission: ducklog.check
        ducklog:
                usage: /ducklog reload
                description: Reload DuckLog settings.
                permission: ducklog.reload
        timetop:
                usage: /timetop [server]
                description: Show the top 10 players by login time, optionally per server.
                permission: ducklog.timetop
        friend:
                usage: /friend <playername>
                description: Displays when the named player was last online.
                permission: ducklog.friend
permissions:
        ducklog.*:
                description: All ducklog permissions.
                default: op
                children:
                        - ducklog.seen
                        - ducklog.audit
                        - ducklog.check
                        - ducklog.reload
                        - ducklog.timetop
                        - ducklog.friend
        ducklog.seen:
                description: Allow usage of the /seen command.
                default: op
        ducklog.seen.ip:
                description: Allow usage of the /seen command with ip addresses.
                default: op
        ducklog.audit:
                description: Allow usage of the /audit command.
                default: op
        ducklog.check:
                description: Allow usage of the /check command on self.
                default: true
        ducklog.check.other:
                description: Allow usage of the /check command on others.
                default: op
        ducklog.reload:
                description: Allow usage of the /ducklog command.
                default: op
        ducklog.timetop:
                description: Allow usage of the /timetop command.
                default: op
        ducklog.friend:
                description: Allow usage of the /friend command.
                default: true